default_context:
  project_name: 'workout'
  project_slug: 'workout'
  domain_main: 'workout.bennettgarner.com'
  domain_staging: 'stag.workout.bennettgarner.com'
  docker_swarm_stack_name_main: 'workout-bennettgarner-com'
  docker_swarm_stack_name_staging: 'stag-workout-bennettgarner-com'
  secret_key: 'c757ddf3e209fafe3cad6fae7eaf87592d28e7dfd34bad3a2fbef52708ebcee7'
  first_superuser: 'bennett.garner@gmail.com'
  first_superuser_password: '4rtg7uik'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.workout.bennettgarner.com", "https://stag.workout.bennettgarner.com", "https://workout.bennettgarner.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@workout.bennettgarner.com'
  postgres_password: '4rtg7uik'
  pgadmin_default_user: 'bennett.garner@gmail.com'
  pgadmin_default_user_password: '4rtg7uik'
  traefik_constraint_tag: 'workout.bennettgarner.com'
  traefik_constraint_tag_staging: 'stag.workout.bennettgarner.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:4rtg7uik'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
